
builds:
  - binary: migration
    main: cmd/migration/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -a 
      - -installsuffix 
      - cgo
    ldflags:
     - -X cmd.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
release:
  github:
    owner: gosidekick
    name: migration