
builds:
  - binary: migration
    main: cmd/migration/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -a 
      - -installsuffix 
      - cgo
      - -mod=vendor
    ldflags: -X github.com/gosidekick/migration/v2/cmd.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
release:
  github:
    owner: gosidekick
    name: migration