
builds:
  - binary: migration
    main: cmd/migration/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -a 
      - -installsuffix 
      - cgo
      - -mod=vendor
    ldflags: -X github.com/gosidekick/migration/v2/cmd.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - migration
    image_templates:
    - "gosidekick/migration:latest"
    - "gosidekick/migration:{{ .Tag }}"
    - "gosidekick/migration:v{{ .Major }}"
    - "gosidekick/migration:v{{ .Major }}.{{ .Minor }}"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
release:
  github:
    owner: gosidekick
    name: migration