sudo: false
dist: trusty
language: go

services:
  - postgresql

os:
  - linux

go:
  - "1.12.x"

install: true

before_script:
  - psql -c 'create database test;' -U postgres

script:
  - GO111MODULE=on go test -mod=vendor -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    go: "1.12.x"